src/DataLoader/DataLoader.cs
- Bug fix
The strategies used by `DataLoader` are not disposed.
The strategies used by `DataLoader` are disposed.
=> Add missing dispose in DataLoader

build/azure-pipelines.yml, build/stage-release.yml
- Build or CI related changes
Fix the release process on Nuget.org
=> Fix the release process

CHANGELOG.md, src/DataLoader.Uno/DataLoader.Uno.csproj
Update Android Target to 10.0 supported since Uno 2.3
=> Update Target to Android 10

.editorconfig, README.md, src/DataLoader.Tests/Core/Integration/DataLoaderTests.cs, src/DataLoader.Tests/Core/Integration/ManualDataLoaderTriggerTests.cs, src/DataLoader.Tests/Core/Integration/ObservableDataLoaderTriggerTests.cs, src/DataLoader.Tests/DataLoader.Tests.csproj
Documentation content changes
No documentation.
Starting documentation.
=> Adds tests and documentation.

src/DataLoader.DynamicMvvm/DataLoader.DynamicMvvm.csproj, src/DataLoader.DynamicMvvm/IViewModelExtensions.Commands.cs, src/DataLoader.Tests/DataLoader.Tests.csproj
- Other, please describe: Package version upgrade
=> Update DynamicMvvm packages

src/DataLoader.Uno/DataLoader.Uno.csproj
Other, please describe:
Update Uno.UI version
Using version 3.1.6 of Uno.UI
Using version 3.1.0-beta.84 of Uno.UI
=> chore: Update to Uno.UI version 3.1.0-beta.84

CHANGELOG.md, build/azure-pipelines.yml, build/gitversion.yml, src/DataLoader.Uno/DataLoader.Uno.csproj
Feature : Adds support for Android 11
No support for Android 11.
Support for Android 11.
~~- [ ] Automated Unit / Integration tests for the changes have been added/updated~~
=> feat: Adds support for Android 11

src/DataLoader.Uno/DataLoaderViewState.cs
- Feature 
- There is no copy constructor for `DataLoaderViewState`.
- There is a copy constructor for `DataLoaderViewState`.
=> Add copy ctor to DataLoaderViewState

src/DataLoader.DynamicMvvm/Triggers/DynamicCommandDataLoaderTrigger.cs, src/DataLoader.DynamicMvvm/Triggers/DynamicPropertyDataLoaderTrigger.cs
- Documentation content changes
=> doc: Improve documentation for DynamicMvvm triggers

src/DataLoader.DynamicMvvm/DataLoader.DynamicMvvm.csproj, src/DataLoader.DynamicMvvm/IViewModelExtensions.DataLoader.cs, src/DataLoader.Tests/DataLoader.Tests.csproj, src/DataLoader.Tests/DynamicMvvm/Integration/ViewModelTests.cs
- Feature
- Update Chinook.DynamicMvvm dependency.
- Fix name confusion in `GetOrCreateDataLoader`.
=> chore: Update Chinook.DynamicMvvm and adjust tests.

src/DataLoader.DynamicMvvm/DataLoader.DynamicMvvm.csproj, src/DataLoader.DynamicMvvm/IViewModelExtensions.Commands.cs, src/DataLoader.Tests/DataLoader.Tests.csproj
- Build or CI related changes
- Update Update Chinook.DynamicMvvm package references
=> chore: Update Chinook.DynamicMvvm package references.

src/DataLoader.Uno/DataLoaderViewState.cs
Bug fix 
We can't change the request property on DataLoaderViewState.
We can change the request property on DataLoaderViewState.
=> fix: we couldn't change Request property on DataLoaderViewState

src/DataLoader.Uno/DataLoaderView.Properties.cs, src/DataLoader.Uno/DataLoaderView.cs, src/DataLoader.Uno/DataLoaderViewController.cs, src/DataLoader.Uno/DataLoaderViewState.cs, src/DataLoader.Uno/IDataLoaderViewDelegate.cs
- Feature
- Refactoring (no functional changes, no api changes) 
The logic of `DataLoaderView` is not reusable.
`DataLoaderViewController` can be used to implement custom DataLoader recipes in the view layer.
=> feat: Extract the logic of DataLoaderView into a controller to ease reuse.

CHANGELOG.md, build/azure-pipelines.yml, build/gitversion.yml, src/DataLoader.Uno/DataLoader.Uno.csproj
- Feature
Chinook.DataLoader Targets Uno.UI 3.1.0-beta.84
Chinook.DataLoader Targets Uno.UI 4.0.7
N/A
=> chore: bump to uno 4

Directory.Build.targets, build/stage-build.yml, src/DataLoader.Abstractions/DataLoader.Abstractions.csproj, src/DataLoader.DynamicMvvm/DataLoader.DynamicMvvm.csproj, src/DataLoader.Uno/DataLoader.Uno.csproj, src/DataLoader/DataLoader.csproj
Feature
- Enabled source link 
- Applied workaround through [Directory.Build.targets](https://github.com/clairernovotny/DeterministicBuilds#work-around-for-net-sdk-prior-31300)
- Enabled flag for `ContinuousIntegrationBuild ` 
- Source Link is not enabled for this nuget package
- Source Link is enabled for this nuget package 
=> feat: enable source link

src/DataLoader.Tests/DynamicMvvm/Integration/DataLoaderViewModelExtensionsTests.cs
…oaderState
Tests
Missing test from this fix #38
There are now tests related with this fix #38
=> test: add missing test from GetFromDataLoaderState fix

build/gitversion.yml
- Build or CI related changes
The latest version is pointing to a feature-branch.
The latest version will be pointing to the main branch.
=> build: Bump version.

src/DataLoader.Tests/Core/Unit/OnDataLostDataLoaderStrategyTests.cs, src/DataLoader/Strategies/OnDataLostDataLoaderStrategy.cs
- Bug fix
When a `DataLoader` loads 2 requests concurrently in a way that the second request finishes before the first request, the `OnDataLostDataLoaderStrategy` can lose the wrong data.
`OnDataLostDataLoaderStrategy` now checks for the latest data in order to lose the correct data.
=> fix: Fix a concurrency bug in OnDataLostDataLoaderStrategy.

.mergify.yml, CONTRIBUTING.md, build/gitversion.yml, build/stage-build.yml, src/DataLoader.Abstractions/DataLoader.Abstractions.csproj, src/DataLoader.DynamicMvvm/DataLoader.DynamicMvvm.csproj, src/DataLoader.Uno.WinUI/DataLoader.Uno.WinUI.csproj, src/DataLoader.Uno/DataLoader.Uno.csproj, src/DataLoader/DataLoader.csproj
chore: cleanup project
- Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
- Public members were removed or renamed.
- Public method signatures were changed or renamed.
- Public constructs, members, or overloads were added.
- A bug in behavior was fixed.
- Documentation was changed.
- Only code under the `build` folder was changed.
- Only code under the `.github` folder was changed.
Please check that your PR fulfills the following requirements:
=> chore: cleanup project

README.md
- Add shields to readme (version and downloads).
- Add references to other chinook packages.
- Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
- Public members were removed or renamed.
- Public method signatures were changed or renamed.
- Public constructs, members, or overloads were added.
- A bug in behavior was fixed.
- Documentation was changed.
- Only code under the `build` folder was changed.
- Only code under the `.github` folder was changed.
Please check that your PR fulfills the following requirements:
=> ci: Add shields and references to other chinook recipes
